import Foundation
#if canImport(Glibc)
import Glibc
#elseif canImport(Darwin)
import Darwin
#endif

/// Compiles `.swift` mod scripts at runtime into dylibs and loads them.
///
/// A mod script is an ordinary Swift file that `import`s `DoomScripting` and
/// exports a factory returning an opaque, retained mod object:
///
/// ```swift
/// import DoomScripting
///
/// final class MyMod: DoomMod {
///     let name = "my-mod"
///     func onLoad(_ ctx: ModContext) { ctx.console.print("hello") }
/// }
///
/// @_cdecl("doommod_create")
/// public func doommod_create() -> UnsafeMutableRawPointer {
///     Unmanaged.passRetained(MyMod()).toOpaque()
/// }
/// ```
///
/// ## The bridging problem
///
/// The host executable may embed DoomScripting statically while a mod dylib
/// links `libDoomScripting.so`, producing two distinct `DoomMod` protocol
/// descriptors — so the host cannot `as? DoomMod` the returned object.
/// Instead, the compiler appends a generated bridge file to every mod
/// translating `DoomMod` calls into plain C entry points inside the dylib
/// (where its own `DoomMod` conformance is valid). The host then wraps the
/// mod in `LoadedMod`, which forwards through `dlsym`'d function pointers.
public enum ScriptCompiler {

    public enum Error: Swift.Error, CustomStringConvertible {
        case swiftcNotFound
        case modulesDirNotFound
        case compileFailed(String)
        case dlopenFailed(String)
        case missingSymbol(String)
        public var description: String {
            switch self {
            case .swiftcNotFound: return "swiftc not found in PATH"
            case .modulesDirNotFound:
                return "could not locate the DoomScripting swiftmodule; " +
                     "set SWIFT_DOOM_MODULES to the build Modules dir " +
                     "(e.g. .build/debug/Modules)"
            case .compileFailed(let s): return "mod compile failed:\n\(s)"
            case .dlopenFailed(let s): return "dlopen failed: \(s)"
            case .missingSymbol(let s): return "mod does not export \(s)"
            }
        }
    }

    /// Bridge source appended to every compiled mod. It assumes the mod
    /// file defines `doommod_create() -> UnsafeMutableRawPointer`.
    static let bridgeSource = """
    // ---- auto-generated by DoomScripting.ScriptCompiler; do not edit ----
    import DoomScripting
    #if canImport(Glibc)
    import Glibc
    #elseif canImport(Darwin)
    import Darwin
    #endif

    @inline(__always)
    private func _doommod_obj(_ o: UnsafeMutableRawPointer) -> DoomMod {
        Unmanaged<AnyObject>.fromOpaque(o).takeUnretainedValue() as! DoomMod
    }
    @inline(__always)
    private func _doommod_ctx(_ p: UnsafeMutableRawPointer) -> ModContext {
        Unmanaged<ModContext>.fromOpaque(p).takeUnretainedValue()
    }

    @_cdecl("doommod_name")
    public func doommod_name(_ o: UnsafeMutableRawPointer) -> UnsafeMutablePointer<CChar>? {
        strdup(_doommod_obj(o).name)
    }
    @_cdecl("doommod_version")
    public func doommod_version(_ o: UnsafeMutableRawPointer) -> UnsafeMutablePointer<CChar>? {
        strdup(_doommod_obj(o).version)
    }
    @_cdecl("doommod_on_load")
    public func doommod_on_load(_ o: UnsafeMutableRawPointer, _ c: UnsafeMutableRawPointer) {
        _doommod_obj(o).onLoad(_doommod_ctx(c))
    }
    @_cdecl("doommod_on_tick")
    public func doommod_on_tick(_ o: UnsafeMutableRawPointer, _ c: UnsafeMutableRawPointer) {
        _doommod_obj(o).onTick(_doommod_ctx(c))
    }
    @_cdecl("doommod_on_map_loaded")
    public func doommod_on_map_loaded(_ o: UnsafeMutableRawPointer,
                                      _ c: UnsafeMutableRawPointer,
                                      _ n: UnsafePointer<CChar>) {
        _doommod_obj(o).onMapLoaded(_doommod_ctx(c), mapName: String(cString: n))
    }
    @_cdecl("doommod_on_unload")
    public func doommod_on_unload(_ o: UnsafeMutableRawPointer, _ c: UnsafeMutableRawPointer) {
        _doommod_obj(o).onUnload(_doommod_ctx(c))
    }
    @_cdecl("doommod_destroy")
    public func doommod_destroy(_ o: UnsafeMutableRawPointer) {
        Unmanaged<AnyObject>.fromOpaque(o).release()
    }
    """

    /// Find the Modules dir containing DoomScripting.swiftmodule.
    public static func findModulesDir(extra: String? = nil) -> String? {
        var candidates: [String] = []
        if let extra { candidates.append(extra) }
        if let env = ProcessInfo.processInfo.environment["SWIFT_DOOM_MODULES"] {
            candidates.append(env)
        }
        let cwd = FileManager.default.currentDirectoryPath
        candidates.append(contentsOf: [
            "\(cwd)/.build/debug/Modules",
            "\(cwd)/.build/release/Modules",
            "\(cwd)/.build/x86_64-unknown-linux-gnu/debug/Modules",
            "\(cwd)/.build/x86_64-unknown-linux-gnu/release/Modules",
            "\(cwd)/.build/x86_64-apple-macosx/debug/Modules",
            "\(cwd)/.build/x86_64-apple-macosx/release/Modules",
        ])
        // walk up from cwd looking for .build/*/Modules
        var dir = cwd
        for _ in 0..<5 {
            for conf in ["debug", "release"] {
                candidates.append("\(dir)/.build/\(conf)/Modules")
            }
            dir = (dir as NSString).deletingLastPathComponent
        }
        for c in candidates {
            if FileManager.default.fileExists(atPath: "\(c)/DoomScripting.swiftmodule") {
                return c
            }
        }
        return nil
    }

    /// Directory containing libDoomScripting (for -L / -l).
    public static func findLibraryDir(modulesDir: String) -> String {
        (modulesDir as NSString).deletingLastPathComponent
    }

    /// Compile and load a mod script. Returns the mod instance.
    @discardableResult
    public static func compileAndLoad(path: String, modulesDir: String? = nil) throws -> DoomMod {
        guard let mdir = modulesDir ?? findModulesDir() else {
            throw Error.modulesDirNotFound
        }
        let libDir = findLibraryDir(modulesDir: mdir)
        let srcURL = URL(fileURLWithPath: path)
        let modName = "doommod_" + String(abs(srcURL.path.hashValue & 0xFFFFFF), radix: 16)
        let outDir = NSTemporaryDirectory() + "swift-doom-mods"
        try? FileManager.default.createDirectory(atPath: outDir, withIntermediateDirectories: true)
        let outPath = "\(outDir)/lib\(modName).so"
        let bridgePath = "\(outDir)/\(modName)_bridge.swift"
        try bridgeSource.write(toFile: bridgePath, atomically: true, encoding: .utf8)

        let args = [
            "swiftc", "-emit-library",
            "-module-name", modName,
            srcURL.path, bridgePath,
            "-I", mdir,
            "-L", libDir, "-lDoomScripting",
            "-o", outPath,
            "-Xlinker", "-rpath", "-Xlinker", libDir,
        ]

        let proc = Process()
        proc.executableURL = URL(fileURLWithPath: "/usr/bin/env")
        proc.arguments = args
        let errPipe = Pipe()
        proc.standardError = errPipe
        proc.standardOutput = errPipe
        do {
            try proc.run()
        } catch {
            throw Error.swiftcNotFound
        }
        proc.waitUntilExit()
        let errOut = String(data: errPipe.fileHandleForReading.readDataToEndOfFile(), encoding: .utf8) ?? ""
        guard proc.terminationStatus == 0 else {
            throw Error.compileFailed(errOut)
        }

        guard let handle = dlopen(outPath, RTLD_NOW | RTLD_LOCAL) else {
            throw Error.dlopenFailed(String(cString: dlerror()))
        }
        func sym<T>(_ name: String, as t: T.Type) throws -> T {
            guard let p = dlsym(handle, name) else {
                dlclose(handle)
                throw Error.missingSymbol(name)
            }
            return unsafeBitCast(p, to: t)
        }
        typealias Factory = @convention(c) () -> UnsafeMutableRawPointer
        typealias StrFn = @convention(c) (UnsafeMutableRawPointer) -> UnsafeMutablePointer<CChar>?
        typealias CtxFn = @convention(c) (UnsafeMutableRawPointer, UnsafeMutableRawPointer) -> Void
        typealias MapFn = @convention(c) (UnsafeMutableRawPointer, UnsafeMutableRawPointer,
                                          UnsafePointer<CChar>) -> Void
        typealias VoidFn = @convention(c) (UnsafeMutableRawPointer) -> Void
        return try LoadedMod(
            handle: handle,
            obj: sym("doommod_create", as: Factory.self)(),
            nameFn: sym("doommod_name", as: StrFn.self),
            versionFn: sym("doommod_version", as: StrFn.self),
            onLoadFn: sym("doommod_on_load", as: CtxFn.self),
            onTickFn: sym("doommod_on_tick", as: CtxFn.self),
            onMapLoadedFn: sym("doommod_on_map_loaded", as: MapFn.self),
            onUnloadFn: sym("doommod_on_unload", as: CtxFn.self),
            destroyFn: sym("doommod_destroy", as: VoidFn.self))
    }
}

/// A `DoomMod` adapter around a runtime-compiled dylib's C entry points.
final class LoadedMod: DoomMod {
    let handle: UnsafeMutableRawPointer
    let obj: UnsafeMutableRawPointer
    private let nameFn: @convention(c) (UnsafeMutableRawPointer) -> UnsafeMutablePointer<CChar>?
    private let versionFn: @convention(c) (UnsafeMutableRawPointer) -> UnsafeMutablePointer<CChar>?
    private let onLoadFn: @convention(c) (UnsafeMutableRawPointer, UnsafeMutableRawPointer) -> Void
    private let onTickFn: @convention(c) (UnsafeMutableRawPointer, UnsafeMutableRawPointer) -> Void
    private let onMapLoadedFn: @convention(c) (UnsafeMutableRawPointer, UnsafeMutableRawPointer,
                                             UnsafePointer<CChar>) -> Void
    private let onUnloadFn: @convention(c) (UnsafeMutableRawPointer, UnsafeMutableRawPointer) -> Void
    private let destroyFn: @convention(c) (UnsafeMutableRawPointer) -> Void

    init(handle: UnsafeMutableRawPointer, obj: UnsafeMutableRawPointer,
         nameFn: @escaping @convention(c) (UnsafeMutableRawPointer) -> UnsafeMutablePointer<CChar>?,
         versionFn: @escaping @convention(c) (UnsafeMutableRawPointer) -> UnsafeMutablePointer<CChar>?,
         onLoadFn: @escaping @convention(c) (UnsafeMutableRawPointer, UnsafeMutableRawPointer) -> Void,
         onTickFn: @escaping @convention(c) (UnsafeMutableRawPointer, UnsafeMutableRawPointer) -> Void,
         onMapLoadedFn: @escaping @convention(c) (UnsafeMutableRawPointer, UnsafeMutableRawPointer,
                                                UnsafePointer<CChar>) -> Void,
         onUnloadFn: @escaping @convention(c) (UnsafeMutableRawPointer, UnsafeMutableRawPointer) -> Void,
         destroyFn: @escaping @convention(c) (UnsafeMutableRawPointer) -> Void) {
        self.handle = handle; self.obj = obj
        self.nameFn = nameFn; self.versionFn = versionFn
        self.onLoadFn = onLoadFn; self.onTickFn = onTickFn
        self.onMapLoadedFn = onMapLoadedFn; self.onUnloadFn = onUnloadFn
        self.destroyFn = destroyFn
    }

    deinit { destroyFn(obj) } // dylib handle stays open: symbols must stay valid

    private func str(_ f: (UnsafeMutableRawPointer) -> UnsafeMutablePointer<CChar>?) -> String {
        guard let p = f(obj) else { return "" }
        defer { free(p) }
        return String(cString: p)
    }
    var name: String { str(nameFn) }
    var version: String { str(versionFn) }
    func onLoad(_ ctx: ModContext) {
        onLoadFn(obj, Unmanaged.passUnretained(ctx).toOpaque())
    }
    func onTick(_ ctx: ModContext) {
        onTickFn(obj, Unmanaged.passUnretained(ctx).toOpaque())
    }
    func onMapLoaded(_ ctx: ModContext, mapName: String) {
        mapName.withCString { onMapLoadedFn(obj, Unmanaged.passUnretained(ctx).toOpaque(), $0) }
    }
    func onUnload(_ ctx: ModContext) {
        onUnloadFn(obj, Unmanaged.passUnretained(ctx).toOpaque())
    }
}
